In [ ]:
!pip install openai

In [ ]:
pip install translate

In [ ]:
pip install nltk

In [ ]:
import openai
import os
import json
from openai import OpenAI

from translate import Translator
from nltk import word_tokenize, pos_tag
from nltk.corpus import stopwords
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
import re

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

In [5]:
client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key='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',
)

In [6]:
question = '아래의 일기에서 [기분, 날씨, 행동, 사물, 음식, 장소]의 요소들을 각각 추출해서 json 형태로 답변해줘.'
text = input()

In [7]:
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": question + text,
        }
    ],
    model="gpt-3.5-turbo",
)

print(chat_completion)

ChatCompletion(id='chatcmpl-8O0HfBE0brz3bN67lLD2KMjc9JimE', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content='{\n  "기분": "떨리다, 기대하다",\n  "날씨": "자유라다, 자유로움을 느끼다",\n  "행동": "자유시간을 갖다, 방문하다, 사진을 찍다, 기념품을 사다, 걸어가다, 보다, 먹다",\n  "사물": "엄마, 구스타프 클림트의 작품, 벨베데레 궁전 국립 미술관, 시간, 미술 작품, 사진, 슈베르트의 흉상, 젤라또, 빵",\n  "음식": "아인슈페너 커피, 젤라또, 빵",\n  "장소": "오스트리아 빈, 체코 프라하, 벨베데레 궁전 국립 미술관, 공원"\n}', role='assistant', function_call=None, tool_calls=None))], created=1700731655, model='gpt-3.5-turbo-0613', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=281, prompt_tokens=521, total_tokens=802))


In [9]:
question2 = 'key-value 형태의 텍스트에서 value 부분에 해당하는 것들을 영어로 번역해줘'
text2 = chat_completion.choices[0].message.content

chat_completion2 = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": question2 + text2,
        }
    ],
    model="gpt-3.5-turbo",
)

print(chat_completion2)

ChatCompletion(id='chatcmpl-8O0IyU4c4xZoBEBRGUCkeR9kYLJtg', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content='{\n  "기분": "excited, look forward to",\n  "날씨": "feel free, feel freedom",\n  "행동": "have free time, visit, take photos, buy souvenirs, walk, watch, eat",\n  "사물": "mom, Gustav Klimt\'s artwork, Belvedere Palace National Gallery, time, artwork, picture, Schubert\'s portrait, gelato, bread",\n  "음식": "Einspänner coffee, gelato, bread",\n  "장소": "Vienna, Austria, Prague, Czech Republic, Belvedere Palace National Gallery, park"\n}', role='assistant', function_call=None, tool_calls=None))], created=1700731736, model='gpt-3.5-turbo-0613', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=141, prompt_tokens=317, total_tokens=458))


In [13]:
# json_text = chat_completion2.choices[0].message.content
# JSON 문자열을 딕셔너리로 파싱
# print(json_text)
# data_dict = json.loads(json_text)
# print(data_dict)

import ast
data_dict = ast.literal_eval(chat_completion2.choices[0].message.content)

# data_dict는 이제 JSON 데이터를 파싱하여 얻은 딕셔너리입니다.
# print(data_dict)
# print(data_dict['기분'])
# print(data_dict['날씨'])
# print(data_dict['행동'])
# print(data_dict['사물'])
# print(data_dict['음식'])
# print(data_dict['장소'])

data_dict_list = [data_dict['기분'], data_dict['날씨'], data_dict['행동'], data_dict['사물'], data_dict['음식'],data_dict['장소']]
기분 = []
날씨 = []
행동 = []
사물 = []
음식 = []
장소 = []
# save_list에 각 리스트를 추가
save_list = [기분, 날씨, 행동, 사물, 음식, 장소]

s = 0
# 텍스트를 ',' 구분자로 나누어 리스트로 변환
for data_dict_ele in data_dict_list:
    values_list = data_dict_ele.split(', ')

    # save_list의 각 리스트에 값을 추가
    for i in range(len(values_list)):
        save_list[s].append(word_tokenize(values_list[i]))
    s+=1

save_list = [item for sublist in save_list for subsublist in sublist for item in subsublist]

# 결과 출력
for saved_data in set(save_list):
    print(saved_data)

freedom
Einspänner
have
souvenirs
Belvedere
bread
coffee
Czech
time
excited
watch
Gallery
Gustav
buy
photos
free
forward
Schubert
mom
gelato
Austria
artwork
Prague
visit
Vienna
park
look
feel
National
Republic
walk
Palace
take
portrait
's
to
picture
eat
Klimt


# 추론 과정

In [ ]:
!apt install libomp-dev
!pip install faiss-cpu
!pip install pandas
!pip install numpy
!pip install torch
!pip install transformers

In [22]:
print(save_list)

['excited', 'look', 'forward', 'to', 'feel', 'free', 'feel', 'freedom', 'have', 'free', 'time', 'visit', 'take', 'photos', 'buy', 'souvenirs', 'walk', 'watch', 'eat', 'mom', 'Gustav', 'Klimt', "'s", 'artwork', 'Belvedere', 'Palace', 'National', 'Gallery', 'time', 'artwork', 'picture', 'Schubert', "'s", 'portrait', 'gelato', 'bread', 'Einspänner', 'coffee', 'gelato', 'bread', 'Vienna', 'Austria', 'Prague', 'Czech', 'Republic', 'Belvedere', 'Palace', 'National', 'Gallery', 'park']


In [ ]:
import pickle

# load
with open('emojiDPR/vector_set.pickle', 'rb') as f:
    vector_set = pickle.load(f)
vector_set

In [ ]:

# %%
import faiss
import pandas as pd
import numpy as np

# %% [markdown]
# ### 🪷 faiss metric으로 output token과 emoji의 유사성 계산

# %%
# from google.colab import drive
# drive.mount('/content/drive/')

vectors = []
df = pd.read_csv('emoji_vector_unicode직접기입.csv')


# %%
import torch

vector_set = np.array(vector_set)
vector_set = vector_set.astype('float32')
print(vector_set.shape)

# change vector type from numpy array to torch tensor
# vector_set = torch.tensor(vector_set)

# %%
#vector_array = vector_set.astype(np.float32)

# %% [markdown]
# ---

# %%
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("augustinLib/text-emoji-encoder")
model = AutoModelForSequenceClassification.from_pretrained("augustinLib/text-emoji-encoder")

# %%
import torch

# %% [markdown]
# 이 시점에서 data_list 불러오기

# %%
input_sequence = save_list
print(input_sequence)
tokenized_input = tokenizer(input_sequence, return_tensors="pt", padding='max_length')
logits = model(input_ids = tokenized_input.input_ids,
               attention_mask = tokenized_input.attention_mask).logits

query_vector = logits.detach().numpy()

# %%
dimension = 300
faiss_index = faiss.IndexFlatIP(dimension)
faiss_index = faiss.IndexIDMap(faiss_index)
print(faiss_index.ntotal)

faiss_index.add_with_ids(vector_set, np.arange(len(vector_set)))

In [39]:
# %%
Distance, Index = faiss_index.search(query_vector, 10)

# %%
print(f'Index:{Index}')
print(f'Distance:{Distance}')

# %%
df.loc[Index[0], :]

Index:[[ 542   79  702   58 1451 1545  667 1378  207 1643]
 [  71   19 1001  544 1451 1507  730 1472  989  301]
 [1499   45 1594  667 1449 1597 1639 1624 1632 1635]
 [ 241  561  121  619 1002  543  681  266  816  794]
 [ 121 1176 1076   19 1502 1210 1288 1458 1183 1423]
 [1076 1320  619  789   55 1176 1082  793  924  956]
 [ 121 1176 1076   19 1502 1210 1288 1458 1183 1423]
 [1451   79 1176  542 1577 1580  741 1488 1430  989]
 [ 561 1176  121  130 1045  211 1076  511  241  737]
 [1076 1320  619  789   55 1176 1082  793  924  956]
 [ 209 1351  817  497  412  279  680   14  200  913]
 [ 225 1176 1451 1577  953  235 1290 1430  657  134]
 [ 681 1176 1320 1288 1096 1335  924 1451 1076 1062]
 [  42  839 1161  781  778 1021 1163  657  815  681]
 [1451 1176 1059 1076  619 1623 1637 1220 1657 1127]
 [1451 1127  825 1045 1220 1338 1139 1507 1062  984]
 [1308 1320 1435 1458 1215 1650 1635 1627 1575 1632]
 [ 337 1021 1338 1591 1451  134 1155 1012 1163  963]
 [1176  230  806 1502 1222 1298 1076  69

emoji                                             vector  \
542      😨  [1.397860050201416, 1.2115012407302856, 1.3717...   
79       😟  [2.055026054382324, 1.785905122756958, 1.29455...   
702      🤠  [0.7318504452705383, -0.9581297039985657, -0.8...   
58       😹  [1.2121710777282715, -0.12761124968528748, 0.6...   
1451     🈸  [-0.9282887578010559, 0.8470415472984314, -0.5...   
1545    ⌛️  [0.7798686027526855, 0.8109786510467529, -0.84...   
667      🔫  [-0.50375896692276, 1.0474231243133545, 1.2947...   
1378     ⌛  [0.7991892695426941, 0.9226230978965759, -0.77...   
207      😒  [2.11527681350708, 1.348077654838562, -0.39088...   
1643    💪🏼  [-0.036731913685798645, 0.07911742478609085, -...   

                                            emoji_names  \
542   ['scared', 'frightened', 'fearful', 'surprised...   
79    ['worried face', 'nervous', 'worried', 'distre...   
702                  ['face with cowboy hat', 'cowboy']   
58    ['happy tears cat', 'tears', 'joy', 'laughing ...   
1451     ['申', 'request', 'monkey', 'application form']   
1545                                      ['hourglass']   
667                       ['pistol', 'gun', 'revolver']   
1378                                      ['hourglass']   
207   ['unamused', 'unamused face', 'lame', 'depress...   
1643                      ['light brown flexed biceps']   

                        Unicode  
542              b'\\U0001f628'  
79               b'\\U0001f61f'  
702              b'\\U0001f920'  
58               b'\\U0001f639'  
1451             b'\\U0001f238'  
1545          b'\\u231b\\ufe0f'  
667              b'\\U0001f52b'  
1378                 b'\\u231b'  
207              b'\\U0001f612'  
1643  b'\\U0001f4aa\\U0001f3fc'